name: check

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: "nix flake check"
    strategy:
      matrix:
        host: 
        - macos-latest
        - ubuntu-latest
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@v17
      with:
        extra-conf: |
          accept-flake-config = true
    - uses: cachix/cachix-action@v15
      with:
        name: rvolosatovs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -L --show-trace
