name: check

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: "nix flake check"
    strategy:
      matrix:
        host: 
        - macos-12
        - ubuntu-22.04
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v3
    - uses: nixbuild/nix-quick-install-action@v22
      with:
        nix_conf: |
          accept-flake-config = true
          access-tokens = github.com=${{ github.token }}
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v12
      with:
        name: rvolosatovs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -L --show-trace
